-- Projet Cloud --
DROP DATABASE IF EXISTS `cloud-equipe-e`;
CREATE DATABASE `cloud-equipe-e` DEFAULT CHARACTER SET utf8;
USE `cloud-equipe-e`;


CREATE TABLE `position`(
`idPosition` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`lat` DOUBLE NOT NULL,
`lon` DOUBLE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE `user`(
`id` VARCHAR(255) PRIMARY KEY NOT NULL,
`firstName` VARCHAR(100) NOT NULL,
`lastName` VARCHAR(100) NOT NULL,
`birthDay` DATE NOT NULL,
`fkPosition` INT NOT NULL,
CONSTRAINT `fkPositionConstraint` FOREIGN KEY(`fkPosition`) REFERENCES `position`(`idPosition`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;